### ISSUE TITLE
Feature request: Option to change color of legend's text

### ISSUE THREAD

**Issue by gcaria** [python-visualization/branca#130]
This comes from https://github.com/geopandas/geopandas/issues/2897, since `geopandas.GeoDataFrame.explore()` uses `branca`:

I wish I could plot a colormap also on tiles where dense forests have dark colors, but I can't read the colorbar's title and ticks since they are written with a black font.

**Comment by Conengmo** [comment]
Sounds like a good change to have, to be able to style the legend text. Shouldn’t be too complicated. I’m thinking we could:

- add a parameter to hard-code white or black text color
- add a parameter to add any inline CSS
- add a parameter to add a CSS class, so users can define CSS for the legend text elsewhere

I’m inclined to opt for 2. at the moment but I’m open for other opinions.

Help is welcome to work in this!

**Comment by Conengmo** [comment]
Related issue that proposes a background on colormaps: https://github.com/python-visualization/branca/issues/124

**Comment by ThomasBur** [comment]
I made a PR (#160) to resolve the issue, although it only allows [SVG Recognised Colors](https://www.w3.org/TR/SVG11/types.html#ColorKeywords), rather than arbitrary inline CSS like @Conengmo recommended.

I believe that should be sufficient for @gcaria's requirements, and to enable the resolving of [geopandas/geopands#2897](https://github.com/geopandas/geopandas/issues/2897).

This is my first open-source contribution, so feel free to give any advice or tips :)

**Comment by Conengmo** [comment]
Since https://github.com/python-visualization/branca/pull/160 was merged we can close this issue.
