### ISSUE TITLE
package testsuite in pypi tarball

### ISSUE THREAD

**Issue by pgajdos** [python-visualization/branca#59]
Could you please consider to add tests/ into pypi tarball? It can be used by vendors for unit testing the package.

**Comment by Conengmo** [comment]
Hi @pgajdos, you're right, the tests folder is not included. I don't know how we would go about to set that up. Do you?

Alternatively, could vendors use our Github releases, which include tests? E.g. https://github.com/python-visualization/branca/archive/v0.3.1.tar.gz

**Comment by ocefpaf** [comment]
It was a choice we made a long time ago to produce smaller source distro tarballs. Because `folium` is pure python, no compiled parts, testing upstream is probably OK. If you really have to re-run the tests you should go with the GitHub releases like @Conengmo mentioned. We always do complete releases on GH and clean sources on PyPI.

**Comment by pgajdos** [comment]
Okay, thanks for your statement.

**Comment by pgajdos** [comment]
(Of course we have to test; e. g. imagine we will want to integrate new python version -- we need to figure out what modules will break.)

**Comment by ocefpaf** [comment]
That is what I said about upstream testing being OK. If you trust upstream that test will be done for you. Many downstream vendors do a reduced set of tests, like importing the module. The full test suit is nice, but rarely worth running it downstream.
