### ISSUE TITLE
Customizing Size of LinearColormap

### ISSUE THREAD

**Issue by zeyaddeeb** [python-visualization/branca#72]
Is there a way to resize the colormap?

https://github.com/python-visualization/branca/blob/cd2224538aac5aeb6c0dfa145af3886f192f3537/branca/colormap.py#L147

I'm testing this on mobile and it looks a bit off.

**Comment by deeplook** [comment]
I was running into this, too. The `_repr_html_()` method uses a fixed width of 500, which is a bit unfortunate because one cannot use it in an arbitrary context. See this image.

![heatmap_colormaps](https://user-images.githubusercontent.com/1001778/82096751-d60a9280-9701-11ea-98fb-27930a3c3800.gif)

It would be nice to give the colormap instances a width attribute that could be used by the `_repr_html_()` method. A workaround would be to scale the returned SVG which you can using code below, but it will also scale the number labels:

```python
import io
from branca.colormap import step
from ipywidgets import HTML
from reportlab.graphics.renderSVG import drawToString
from svglib.svglib import svg2rlg

colmap = step.Accent_03
drawing = svg2rlg(io.StringIO((colmap._repr_html_())))
drawing.scale(0.5, 1)
scaled_svg = drawToString(drawing)
HTML(scaled_svg)
```

**Comment by Conengmo** [comment]
You're right that currently the color scales have a fixed size. I get that you may want to change that. While looking into this I tried something out to add this functionality. Maybe you want to test it?

If we scale the thing, is the numbers also resizing a good or a bad thing?

**Comment by deeplook** [comment]
Scaled (squeezed or stretched) would be very ugly. One might want to drop them entirely and leave only ticks as an option. In the end it’s a simple mini plot with its own axis which can easily mean introducing a bunch of config options...

**Comment by Conengmo** [comment]
Okay so no scaling then. Can you check out https://github.com/python-visualization/branca/pull/77, see if that works for you?

**Comment by deeplook** [comment]
I'll try, but I don't see any info about building it locally.
