### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/home/keshav/Desktop/application/src/dist/main/branca/_cnames.json'

### ISSUE THREAD

**Issue by mishrakeshav** [python-visualization/branca#83]
I was trying to get executable files of an application that uses folium to display maps. Folium inturn uses Branca. 

This is the description of the system and OS I am using

- Output of pyinstaller --version: 4
- Version of Python: 3.8.5
- Platform: Ubuntu 20.04.1 LTS

This is the minimal example of my application 

```
import folium
print('hello world')
```
I tried the solutions suggested in [https://github.com/pyinstaller/pyinstaller/issues/4809](https://github.com/pyinstaller/pyinstaller/issues/4809) , [https://groups.google.com/g/pyinstaller/c/OYhJdeZ9010/m/vLhYAWUzAQAJ](https://groups.google.com/g/pyinstaller/c/OYhJdeZ9010/m/vLhYAWUzAQAJ), 
and 
[https://github.com/pyinstaller/pyinstaller/issues/5247](https://github.com/pyinstaller/pyinstaller/issues/5247)

**Comment by Conengmo** [comment]
I have no experience with pyinstaller, so I can't help you with that. If there's work needed on branca or folium to make it work better with pyinstaller, that's something we can consider, but somebody would have to do it. Since you seem to be looking for help, you may have to try another place, like Stackoverflow perhaps.

**Comment by mishrakeshav** [comment]
Okay
